spring.application.name=SplitMates

# PORT
server.port=${PORT:8080}

# DB (we will change later)
spring.datasource.url=YOUR_DB_URL
spring.datasource.username=YOUR_DB_USER
spring.datasource.password=YOUR_DB_PASS

# JPA
spring.jpa.hibernate.ddl-auto=update

# EMAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=borhadeparth24@gmail.com
spring.mail.password=oufuyddsxdhsvzlb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# RAZORPAY
razorpay.key=YOUR_KEY
razorpay.secret=YOUR_SECRET